export type BrowserIdentity = {
  family: string;
  version: string;
};

export type BrowserCompatibilityAssessment = {
  browser: BrowserIdentity;
  supported: boolean;
};

export type TestcenterLoadEnvironment = {
  browserVersion: string;
  browserName: string;
  osName: string;
  device: string;
  screenSizeWidth: number;
  screenSizeHeight: number;
  loadTime: number;
};

// Generated by Original Testcenter 18.0 at upstream commit 4d097a88 from its
// production browserslist rules.
// Keep this pinned list in the compatibility corpus so browser policy changes are
// deliberate and reviewable alongside the source system.
export const originalTestcenterSupportedBrowsers = Object.freeze([
  "chrome 151",
  "chrome 150",
  "edge 151",
  "edge 150",
  "firefox 153",
  "firefox 152",
  "firefox 140",
  "ios_saf 26.4",
  "ios_saf 26.3",
  "safari 26.4",
  "safari 26.3"
]);

const browserFamilyLabels: Readonly<Record<string, string>> = {
  chrome: "Chrome",
  edge: "Edge",
  firefox: "Firefox",
  ios_saf: "iOS",
  safari: "Safari"
};

const readVersion = (
  userAgent: string,
  pattern: RegExp,
  underscoreSeparated = false
): string | null => {
  const value = userAgent.match(pattern)?.[1];
  return value
    ? underscoreSeparated
      ? value.replaceAll("_", ".")
      : value
    : null;
};

export const parseBrowserUserAgent = (userAgent: string): BrowserIdentity => {
  const normalized = userAgent.trim();
  if (!normalized) {
    return { family: "Unknown", version: "unknown" };
  }

  if (/iPhone|iPad|iPod/i.test(normalized)) {
    return {
      family: "iOS",
      version:
        readVersion(normalized, /(?:CPU (?:iPhone )?OS|iPhone OS) ([\d_]+)/i, true) ??
        "unknown"
    };
  }

  const candidates: ReadonlyArray<{
    family: string;
    pattern: RegExp;
  }> = [
    { family: "Vivaldi", pattern: /Vivaldi\/([\d.]+)/i },
    { family: "Opera", pattern: /(?:OPR|Opera)\/([\d.]+)/i },
    { family: "Samsung Internet", pattern: /SamsungBrowser\/([\d.]+)/i },
    { family: "Edge", pattern: /(?:EdgA?|Edge)\/([\d.]+)/i },
    { family: "Firefox", pattern: /Firefox\/([\d.]+)/i },
    { family: "Chrome", pattern: /(?:HeadlessChrome|Chrome)\/([\d.]+)/i },
    { family: "Safari", pattern: /Version\/([\d.]+).*Safari\//i },
    { family: "Explorer", pattern: /(?:MSIE |rv:)([\d.]+)(?:\)|;)/i },
    { family: "Mosaic", pattern: /NCSA Mosaic\/([\d.]+)/i }
  ];

  for (const candidate of candidates) {
    const version = readVersion(normalized, candidate.pattern);
    if (version) {
      return { family: candidate.family, version };
    }
  }

  const generic = normalized.match(/^([^/\s]+)\/([\d.]+)/);
  return generic
    ? { family: generic[1], version: generic[2] }
    : { family: "Unknown", version: "unknown" };
};

const parseOperatingSystemName = (userAgent: string): string => {
  const windowsVersionLabels: Readonly<Record<string, string>> = {
    "10.0": "10",
    "6.3": "8.1",
    "6.2": "8",
    "6.1": "7"
  };
  const windowsVersion = userAgent.match(/Windows NT ([\d.]+)/i)?.[1];
  if (windowsVersion) {
    return `Windows ${windowsVersionLabels[windowsVersion] ?? windowsVersion}`;
  }
  const iosVersion = userAgent.match(
    /(?:CPU (?:iPhone )?OS|iPhone OS) ([\d_]+)/i
  )?.[1];
  if (iosVersion) {
    return `iOS ${iosVersion.replaceAll("_", ".")}`;
  }
  const androidVersion = userAgent.match(/Android ([\d.]+)/i)?.[1];
  if (androidVersion) {
    return `Android ${androidVersion}`;
  }
  const macVersion = userAgent.match(/Mac OS X ([\d_]+)/i)?.[1];
  if (macVersion) {
    return `Mac OS ${macVersion.replaceAll("_", ".")}`;
  }
  const chromeOsVersion = userAgent.match(/CrOS [^;)]+ ([\d.]+)/i)?.[1];
  if (chromeOsVersion) {
    return `Chromium OS ${chromeOsVersion}`;
  }
  if (/Linux/i.test(userAgent)) {
    return "Linux --";
  }
  return "--";
};

const parseDeviceName = (userAgent: string): string => {
  if (/iPhone/i.test(userAgent)) {
    return "Apple iPhone mobile";
  }
  if (/iPad/i.test(userAgent)) {
    return "Apple iPad tablet";
  }
  if (/Android/i.test(userAgent)) {
    const model = userAgent
      .match(/Android [^;)]*;\s*([^;)]+?)(?:\s+Build\/[^;)]*)?[;)]/i)?.[1]
      ?.trim();
    return [model, /Mobile/i.test(userAgent) ? "mobile" : "tablet"]
      .filter(Boolean)
      .join(" ");
  }
  return "";
};

export const projectTestcenterLoadEnvironment = (input: {
  userAgent: string;
  screenSizeWidth: number;
  screenSizeHeight: number;
  loadTime: number;
}): TestcenterLoadEnvironment => {
  const browser = parseBrowserUserAgent(input.userAgent);
  const mobileSafariVersion = /iPhone|iPad|iPod/i.test(input.userAgent)
    ? readVersion(input.userAgent, /Version\/([\d.]+)/i)
    : null;
  return {
    browserVersion:
      mobileSafariVersion ??
      (browser.version === "unknown" ? "--" : browser.version),
    browserName:
      mobileSafariVersion != null
        ? "Mobile Safari"
        : browser.family === "Unknown"
          ? "--"
          : browser.family,
    osName: parseOperatingSystemName(input.userAgent),
    device: parseDeviceName(input.userAgent),
    screenSizeWidth: Math.max(0, Math.round(input.screenSizeWidth)),
    screenSizeHeight: Math.max(0, Math.round(input.screenSizeHeight)),
    loadTime: Math.max(0, Math.round(input.loadTime))
  };
};

const normalizeFamily = (family: string): string =>
  family.trim().toLocaleLowerCase();

const parseVersion = (version: string): number[] | null => {
  const parts = version.match(/\d+/g)?.slice(0, 3).map(Number);
  return parts?.length ? parts : null;
};

const compareVersions = (left: string, right: string): number | null => {
  const leftParts = parseVersion(left);
  const rightParts = parseVersion(right);
  if (!leftParts || !rightParts) {
    return null;
  }
  for (let index = 0; index < 3; index += 1) {
    const difference = (leftParts[index] ?? 0) - (rightParts[index] ?? 0);
    if (difference !== 0) {
      return Math.sign(difference);
    }
  }
  return 0;
};

const parseSupportedBrowser = (entry: string): BrowserIdentity | null => {
  const separator = entry.lastIndexOf(" ");
  if (separator <= 0 || separator === entry.length - 1) {
    return null;
  }
  const family = entry.slice(0, separator);
  const version = entry.slice(separator + 1);
  return parseVersion(version)
    ? { family: browserFamilyLabels[family] ?? family, version }
    : null;
};

export const browserMatchesSupportedList = (
  browser: BrowserIdentity,
  supportedBrowsers: readonly string[] = originalTestcenterSupportedBrowsers,
  allowHigherVersions = true
): boolean => {
  const parsedSupportedBrowsers = supportedBrowsers
    .map(parseSupportedBrowser)
    .filter((entry): entry is BrowserIdentity => entry != null);
  if (parsedSupportedBrowsers.length === 0) {
    return true;
  }

  return parsedSupportedBrowsers.some(supportedBrowser => {
    if (normalizeFamily(browser.family) !== normalizeFamily(supportedBrowser.family)) {
      return false;
    }
    const comparison = compareVersions(browser.version, supportedBrowser.version);
    return comparison != null && (allowHigherVersions ? comparison >= 0 : comparison === 0);
  });
};

export const assessBrowserCompatibility = (
  userAgent: string,
  supportedBrowsers: readonly string[] = originalTestcenterSupportedBrowsers
): BrowserCompatibilityAssessment => {
  const browser = parseBrowserUserAgent(userAgent);
  return {
    browser,
    supported: browserMatchesSupportedList(browser, supportedBrowsers)
  };
};
